apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fraud-detection
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fraud-detection
        version: v1
        type: server
    spec:
      containers:
      - name: fraud-detection
        env:
        - name: AMQ_LOCATION_KEY
          value: ONSTAGE
        - name: AMQ_INITIAL_RATE
          value: "200"
        image: tedross/amq-demo-server:0.4
        imagePullPolicy: IfNotPresent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-load
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client-load
        version: v1
        type: server
    spec:
      containers:
      - name: client-load
        env:
        - name: AMQ_LOCATION_KEY
          value: ONSTAGE
        image: tedross/amq-demo-client:0.4
        imagePullPolicy: IfNotPresent
