apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: qdr
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: qdr-external-cert
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 55672
    name: inter-router
  selector:
    type: qdrouterd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qdr
        version: v1
        type: qdrouterd
    spec:
      containers:
      - name: qdr
        env:
        - name: AMQ_LOCATION_KEY
          value: AZR
        image: gordons/qdr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: internal-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/internal
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: internal-certs
        secret:
          secretName: qdr-internal-cert
