apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fraud-detection
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fraud-detection
        version: v1
        type: server
    spec:
      containers:
      - name: fraud-detection
        env:
        - name: AMQ_LOCATION_KEY
          value: AWS
        - name: AMQ_INITIAL_RATE
          value: "10"
        image: tedross/amq-demo-server:0.5
        imagePullPolicy: IfNotPresent
